# start FROM a base layer of node v10.15
FROM node:10.15

# Check node version
RUN node -v

# Install webpack dev server
RUN npm install webpack -g

# Install db-migrate
RUN npm install db-migrate -g

# Working directory for application
WORKDIR /usr/src/app

# npm install into /usr/src/app
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json /usr/src/app/
RUN npm rebuild node-sass
RUN npm install

# replace this with your application's default port
EXPOSE 3000