// user action types
export const UPDATE_SIGNUP_USERNAME = 'UPDATE_SIGNUP_USERNAME';
export const UPDATE_SIGNUP_PASSWORD = 'UPDATE_SIGNUP_PASSWORD';
export const UPDATE_SIGNUP_EMAIL = 'UPDATE_SIGNUP_EMAIL';
export const SUBMIT_SIGNUP = 'SUBMIT_SIGNUP';
export const SUCCESSFUL_SIGNUP = 'SUCCESSFUL_SIGNUP';
export const FAILED_SIGNUP = 'FAILED_SIGNUP';
export const UPDATE_LOGIN_EMAIL = 'UPDATE_LOGIN_EMAIL';
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SUCCESSFUL_AUTH_VERIFICATION = 'SUCCESSFUL_AUTH_VERIFICATION';
export const FAILED_AUTH_VERIFICATION = 'FAILED_AUTH_VERIFICATION';
export const RESET_LOGIN_INFO = 'RESET_LOGIN_INFO';
export const RESET_SIGNUP_INFO = 'RESET_SIGNUP_INFO';
export const SET_SIGNUP_CREDENTIAL_ERRORS = 'SET_SIGNUP_CREDENTIAL_ERRORS';
export const UPDATE_FORGOT_INPUT_EMAIL = 'UPDATE_FORGOT_INPUT_EMAIL';
export const EMAIL_SUCCESSFULLY_SENT = 'EMAIL_SUCCESSFULLY_SENT';
export const EMAIL_FAILED_TO_SEND = 'EMAIL_FAILED_TO_SEND'; 
export const UPDATE_FIRST_NEW_PASSWORD = 'UPDATE_FIRST_NEW_PASSWORD';
export const UPDATE_SECOND_NEW_PASSWORD = 'UPDATE_SECOND_NEW_PASSWORD';
export const SET_NEW_PASSWORD_ERRORS = 'SET_NEW_PASSWORD_ERRORS';

// game config action types
export const GET_GAME_LIST = 'GET_GAME_LIST';
export const DISPLAY_GAME_LIST = 'DISPLAY_GAME_LIST';
export const DISPLAY_GAME_MENU = 'DISPLAY_GAME_MENU';
export const SET_SELECTED_GAME = 'SET_SELECTED_GAME';
export const SUBMIT_GAME_SELECTION = 'SUBMIT_GAME_SELECTION';
export const SUCCESS_PLAY = 'SUCCESS_PLAY';
export const RESET_GAME_SELECTION = 'RESET_GAME_SELECTION';
export const TOGGLE_GAME_CATEGORY = 'TOGGLE_GAME_CATEGORY';
export const TOGGLE_ALL_GAME_CATEGORIES = 'TOGGLE_ALL_GAME_CATEGORIES';
export const SET_GAME_DIFFICULTY = 'SET_GAME_DIFFICULTY';
export const START_GAME = 'START_GAME';
export const RESET_GAME_INITIATION = 'RESET_GAME_INITIATION';
export const GET_CARDS_IFNO = 'GET_CARDS_IFNO';
export const POPULATE_CARDS_ARRAY = 'POPULATE_CARDS_ARRAY';
export const RESET_GAME_MENU = 'RESET_GAME_MENU';
export const SET_YEARS_BOOL = 'SET_YEARS_BOOL';
export const UPDATE_MIN_MAX_YEARS = 'UPDATE_MIN_MAX_YEARS';


// gameplay action types
export const SELECT_ANSWER = 'SELECT_ANSWER';
export const GO_TO_NEXT = 'GO_TO_NEXT';
export const FINISH_GAME = 'FINISH_GAME';
export const SEND_RESULT = 'SEND_RESULT';
export const RESET_GAME = 'RESET_GAME';

// admin actions
export const UPDATE_ADMIN_LOGIN_USERNAME = 'UPDATE_ADMIN_LOGIN_USERNAME';
export const UPDATE_ADMIN_LOGIN_PASSWORD = 'UPDATE_ADMIN_LOGIN_PASSWORD';
export const SUCCESSFUL_ADMIN_LOGIN = 'SUCCESSFUL_ADMIN_LOGIN';
export const FAILED_ADMIN_LOGIN = 'FAILED_ADMIN_LOGIN';
export const ADD_MEDIUM_RULE_CATEGORY = 'ADD_MEDIUM_RULE_CATEGORY';
export const ADD_HARD_RULE_CATEGORY = 'ADD_HARD_RULE_CATEGORY';
export const REMOVE_MEDIUM_RULE_CATEGORY = 'REMOVE_MEDIUM_RULE_CATEGORY';
export const REMOVE_HARD_RULE_CATEGORY = 'REMOVE_HARD_RULE_CATEGORY';
export const UPDATE_NEW_MEDIUM_RULE = 'UPDATE_NEW_MEDIUM_RULE';
export const UPDATE_NEW_HARD_RULE = 'UPDATE_NEW_HARD_RULE';
export const SUBMIT_ADMIN_LOGIN = 'SUBMIT_ADMIN_LOGIN';

// leaderboard actions
export const CHANGE_LEADERBOARD_DIFFICULTY = 'CHANGE_LEADERBOARD_DIFFICULTY';
export const POPULATE_RESULTS_ARRAY = 'POPULATE_RESULTS_ARRAY';
export const CHANGE_LEADERBOARD_SORT_CATEGORY = 'CHANGE_LEADERBOARD_SORT_CATEGORY';
export const TOGGLE_SORT_DIRECTION = 'TOGGLE_SORT_DIRECTION';
export const RESET_LEADERBOARD_LOADING_CONTENT = 'RESET_LEADERBOARD_LOADING_CONTENT';


